package com.resumeiq.entity;

import com.resumeiq.enums.SuggestionCategory;
import jakarta.persistence.*;
import lombok.*;

/**
 * Actionable resume improvement suggestion generated by the suggestion engine.
 */
@Entity
@Table(name = "suggestions", indexes = {
    @Index(name = "idx_suggestion_score", columnList = "ats_score_id")
})
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class Suggestion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ats_score_id", nullable = false)
    private AtsScore atsScore;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private SuggestionCategory category;

    @Column(nullable = false, length = 1000)
    private String text;

    @Column(nullable = false)
    @Builder.Default
    private Integer priority = 1;  // 1 = highest priority

    @Column(length = 50)
    private String section;  // Which resume section this applies to

    @Column(length = 100)
    private String relatedKeyword;  // Associated missing keyword if any
}
