package com.resumeiq.entity;
import com.resumeiq.enums.SuggestionCategory;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import lombok.*;
/**
 * Actionable resume improvement suggestion generated by the suggestion engine.
 */
@Document
@Table(name = "suggestions", indexes = {
    @Index(name = "idx_suggestion_score", columnList = "ats_score_id")
})
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class Suggestion {
    @Id
    private String id;
    @DBRef(lazy = true)
    private AtsScore atsScore;
    @Enumerated(EnumType.STRING)
    private SuggestionCategory category;
    private String text;
    @Builder.Default
    private Integer priority = 1;  // 1 = highest priority
    private String section;  // Which resume section this applies to
    private String relatedKeyword;  // Associated missing keyword if any
}
